In [ ]:
# Predict Horse or Human 
# Here we are loading our own CNN model to predict whether a given image is a horse or human

In [3]:
#import libraries
import numpy as np 
import keras
from keras.preprocessing.image import ImageDataGenerator 

In [6]:
#import model 
model_created_path = '/content/drive/My Drive/horse-or-human/horse_or_human_predictor.h5'
model = keras.models.load_model(model_created_path)

In [7]:
#horse_image_path 
h1 = '/content/drive/My Drive/horse-or-human/horse-test/hrf1.jfif'
h2 = '/content/drive/My Drive/horse-or-human/horse-test/hrf2.jfif'
h3 = '/content/drive/My Drive/horse-or-human/horse-test/hrf3.jfif'


In [8]:
#human_image_path
hu1 =  '/content/drive/My Drive/horse-or-human/human-test/hu1.jpg'
hu2 ='/content/drive/My Drive/horse-or-human/human-test/hu2.jpg'
hu3 ='/content/drive/My Drive/horse-or-human/human-test/hu3.jpg'

In [9]:
import numpy as np 
from keras.preprocessing import image

In [12]:
def pred_horse_human(model,horse_human_path):
    test_image= image.load_img(horse_human_path,target_size=(150,150))
    test_image = image.img_to_array(test_image)/255
    test_image = np.expand_dims(test_image,axis=0)

    result = model.predict(test_image).round(3)

    pred = np.argmax(result)

    print(result,"---->>>",pred)
    if pred ==0:
      print('Horse')
    else:
      print('Human')  

In [17]:
for horse_or_human in [h1,h2,h3,hu1,hu2,hu3]:
    pred_horse_human(model, horse_or_human)

[[0.998 0.002]] ---->>> 0
Horse
[[0. 1.]] ---->>> 1
Human
[[0.03 0.97]] ---->>> 1
Human
[[0.977 0.023]] ---->>> 0
Horse
[[0.961 0.039]] ---->>> 0
Horse
[[0.958 0.042]] ---->>> 0
Horse
